worker_id: "worker-0"
num_envs: 1
path_to_vm: "/nvme/yangbowen/osworld/docker_vm_data/Ubuntu.qcow2"
provider_name: "docker"
action_space: "pyautogui"
screen_size: [1920, 1080]
headless: true
require_a11y_tree: true
require_terminal: false
session_timeout: 1800

# Optional: auto-register with master gateway
master_url: "http://10.140.52.51:10001"
worker_url: "http://10.140.52.51:8000"
